### ISSUE TITLE
clickstream > initialize: Missing "Create Folder"

### ISSUE THREAD

**Issue by diethardsteiner** [neo4j-examples/kettle-plugin-examples#4]
One the first run after cloning the repo the `${Internal.Entry.Current.Directory}/files` doesn't exist and hence the job at its current state fails. Add a "Create Folder" job entry to initialize.kjb at the beginning and untick *Fail if folder exists*.

**Comment by mattcasters** [comment]
Thank you for reporting this Diethard!
